version: 1
build:
  doNotRunBuildStepIfAppAlreadyBuilt: true
runtime:
  python:
    runtimeVersion: 3.11
    virtualEnvCreateCommand: python -m venv /tmp/venv
    virtualEnvActivateCommand: source /tmp/venv/bin/activate
    packageInstallCommand: pip install -r requirements.txt
    startupCommand: startup.sh
